### ISSUE TITLE
Double header folders created when there are non nested notes

### ISSUE THREAD

**Issue by DoNotResuscitate** [DoNotResuscitate/obsidian-zola#3]
![firefox_2022-11-15_17-50-56](https://user-images.githubusercontent.com/33287665/202041468-35b44045-d8b2-4287-9e5f-c2fa915b2ab5.png)
The notes that are not nested in folders should still be under 1 header rather than duplicating it.

**Comment by DoNotResuscitate** [comment]
@rockmanvnx6 I noticed your site still has this issue too. Is this something you've looked into trying to fix yet?

**Comment by auspham** [comment]
@DoNotResuscitate Yea there is this problem. It's because of the python logic to generate the heading. I'm too busy to fix and mostly only use my obsidian to read anyways so haven't fixed it yet. I'm still dependent on the community to fix :).

If you're using mine then might as well fork from mine. I may fix it one day in the future.

**Comment by auspham** [comment]
Hey @DoNotResuscitate latest commit should fix it https://swe.auspham.dev/

**Comment by DoNotResuscitate** [comment]
@rockmanvnx6 It appears sub folders further down still have the same issue
![Screen Shot 2022-11-17 at 16 37 30](https://user-images.githubusercontent.com/33287665/202565151-94e16be5-ae2d-4c0d-82a2-77f425a8a8fa.png)

If you don't have the time to look into it, I'll take a stab at the HTML maybe next week.

**Comment by DoNotResuscitate** [comment]
Just for clarity sake this is an image from Obsidian
![Screen Shot 2022-11-17 at 16 39 45](https://user-images.githubusercontent.com/33287665/202565455-24405f02-538b-4115-bf22-b7688f42e77d.png)

So the Campaigns file is still separated out.

**Comment by auspham** [comment]
It might be a bit easier if you do it since you can replicate it locally. Please let me know once you fixed so i can merge in.

**Comment by DoNotResuscitate** [comment]
Ah interesting - the folder display seems to completely break past a depth of 3 folders

F > F1 > F2 > File works fine
F > F1 > F2 > F3 > File doesn't show up at all in the sidebar. If you follow a link to the file you can still view it, but there is nothing at all shown in the sidebar @rockmanvnx6

**Comment by auspham** [comment]
Yes past depth of 3 is not really coded, if you see in the html file initially it was hard coded for 2 layers. I added another layer myself. I didn't really expect anyone to use my code besides me so didn't make it dynamically

**Comment by auspham** [comment]
@DoNotResuscitate not sure if you've addressed this problem but I ran into situation when i need to use more than depth of 3. In which I have made it dynamic (depth of n) in my latest commit: https://github.com/rockmanvnx6/obsidian-zola/commit/21c2270608df76f9ad5a6bbdc642a46ac8bc17dd

**Comment by DoNotResuscitate** [comment]
@rockmanvnx6 I had not gotten around to it, so thank you for the code fix.

**Comment by DoNotResuscitate** [comment]
Actually @rockmanvnx6 this doesn't seem to be working properly. I have currently a depth of 4 -
```
Chaos & Conquest/Mystara/Session Notes/Mystara Open Table/Files.md
Chaos & Conquest/Mystara/Session Notes/Hot Springs Island/Files.md
Chaos & Conquest/Mystara/Session Notes/Example 3/Files.md
```
and the sidebar name for `Session Notes` is instead shown as `Mystara` https://imperium-game-board.netlify.app/docs/chaos-conquest/mystara/session-summaries/mystara-open-table/goblin-gully-the-failed-attack-session-1/
![firefox_2023-03-16_00-10-38](https://user-images.githubusercontent.com/33287665/225512374-680f973b-98ec-4466-a4fc-ae50c9f6ee55.png)

You can see the same in this test nesting where I went 6 folders deep https://imperium-game-board.netlify.app/docs/chaos-conquest/mystara/test-depth4/test-depth5/test-depth6/newtest/

This has `Test-depth4` showing as `Mystara`, and then the following folders aren't even properly nested. Instead of 4->5->6 it's `Mystara/Test-depth4/test-depth6/newtest` and https://imperium-game-board.netlify.app/docs/chaos-conquest/mystara/test-depth4/test-depth5/teststs/ is `Mystara/test-depth5/teststs`.
![firefox_2023-03-16_00-19-28](https://user-images.githubusercontent.com/33287665/225513434-6ded1e70-8bc6-4f09-a7fa-0f8f8c39763c.png)

**Comment by auspham** [comment]
@DoNotResuscitate  sorry it's because of a typo in the code. Can you try https://github.com/rockmanvnx6/obsidian-zola/commit/19b3e0139afa8a1a64c9b83f66a304105d2090fd

**Comment by DoNotResuscitate** [comment]
Yup that fixed it @rockmanvnx6 , many thanks.

**Comment by DoNotResuscitate** [comment]
@rockmanvnx6 I FINALLY fixed the issue that was plaguing me in https://github.com/DoNotResuscitate/obsidian-zola/issues/3#issuecomment-1319239015. My latest 2 commits fix the nesting and the dynamic code so there will never be duplicate folders when both folders and files are underneath a folder.

Before 
![firefox_2023-04-20_00-45-41](https://user-images.githubusercontent.com/33287665/233267129-6cfd5c59-be75-4af0-81ef-dba081415a1f.png)
After
![firefox_2023-04-20_01-31-46](https://user-images.githubusercontent.com/33287665/233267225-ab12c6cd-34c1-42dc-9d0f-d5d15f083b07.png)

"The Known World" is a file under "Locations". Previously it split the file(s) and the folder(s) into separate headers named the same.

**Comment by auspham** [comment]
Thanks @DoNotResuscitate, I stumbled upon this problem today and used your fix. Works well!
